branch-defaults:
  master:
    environment: Valuemaids-env 
    group_suffix: null
global:
  application_name: valuemaids_backend 
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: haresh
  repository: null
  sc: git
  workspace_type: Application